// Liste organisée de lieux emblématiques du Japon, référencés par leur titre
// exact d'article sur Wikipédia en français. Garantit d'afficher des sites
// reconnus plutôt que des points OSM obscurs remontés par une recherche
// géographique large.
export const JAPAN_PLACES_WIKIPEDIA_TITLES: string[] = [
  "Tour de Tokyo",
  "Tokyo Skytree",
  "Sensō-ji",
  "Meiji-jingū",
  "Shibuya Crossing",
  "Fushimi Inari-taisha",
  "Kinkaku-ji",
  "Kiyomizu-dera",
  "Arashiyama",
  "Château d'Osaka",
  "Dōtonbori",
  "Itsukushima-jinja",
  "Mont Fuji",
  "Parc de Nara",
  "Tōdai-ji",
  "Château de Himeji",
  "Nikkō Tōshō-gū",
  "Hakone",
  "Grand Bouddha de Kamakura",
  "Dōgo Onsen",
  "Kenroku-en",
  "Château de Matsumoto",
  "Ginza",
  "Akihabara",
  "Parc d'Ueno",
  "Ryōan-ji",
  "Château de Nijō",
  "Ise-jingū",
  "Byōdō-in",
  "Shirakawa-gō",
  "Parc du Mémorial de la Paix de Hiroshima",
  "Gion",
  "Mont Kōya",
  "Château de Kumamoto",
  "Dazaifu Tenman-gū",
  "Shinjuku Gyoen",
];